[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# G.FUNCS.evaluate_play
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
G.E_MANAGER:add_event(Event({
        trigger = 'after',delay = 0.4,
'''
position = "before"
match_indent = true
payload = '''
MANIF.adamant()
'''