[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# SMODS.get_card_areas
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "-- TARGET: add your own CardAreas for joker evaluation"
position = "before"
match_indent = true
payload = "table.insert(t, G.e_paper)"