[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.area then self.area:remove_card(self) end"
position = "before"
match_indent = true
payload = '''
if (self.area == G.hand or self.area == G.play) and not self.debuff and self.seal == "manifold_black" then
    for i = 1, math.min(self.ability.seal.extra.spectrals, G.consumeables.config.card_limit - #G.consumeables.cards) do
        G.E_MANAGER:add_event(Event({trigger = "before", delay = 0.0, func = function()
            if G.consumeables.config.card_limit > #G.consumeables.cards then
                local _spectral = create_card("Spectral", G.consumeables, nil, nil, nil, nil, nil, "blk")
                _spectral:add_to_deck()
                G.consumeables:emplace(_spectral)
            end
        return true end }))
    end
end
'''