[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Adds silence condition
# SMODS.destroy_cards
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "return card:start_dissolve(args.colours) ~= false"
position = "at"
match_indent = true
payload = '''
return card:start_dissolve(args.colours, args.should_silence and args.should_silence(args.i)) ~= false
'''

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "if args.immediate then"
position = "before"
match_indent = true
payload = '''
args.i = i
'''