[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Adds silence condition
# SMODS.destroy_cards
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "function SMODS.destroy_cards(cards, bypass_eternal, immediate, skip_anim)"
position = "at"
match_indent = true
payload = '''
function SMODS.destroy_cards(cards, bypass_eternal, immediate, skip_anim, should_silence)
'''

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "cards[i]:start_dissolve()"
position = "at"
match_indent = true
payload = '''
cards[i]:start_dissolve(nil, should_silence and should_silence(i, cards[i]))
'''