[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# end_round
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
-- context.end_of_round calculations
'''
position = "before"
match_indent = true
payload = '''
if G.GAME.round_resets.blind == G.P_BLINDS.bl_manifold_final_aether then
    local count = 0
    for k, v in pairs(G.GAME.blind.hands) do
        count = count + 1
    end
    if count < math.max(math.min(5, G.GAME.round_resets.hands), 0) then
        game_over = true
    end
end
'''

# Game:update
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "{n=G.UIT.O, config={object = DynaText({scale = 0.7, string = localize('ph_unscored_hand'), maxw = 9, colours = {G.C.WHITE},float = true, shadow = true, silent = true, pop_in = 0, pop_in_rate = 6})}},"
position = "at"
match_indent = true
payload = '''
{n = G.UIT.O, config = {object = DynaText{scale = 0.7, string = G.GAME.round_resets.blind == G.P_BLINDS.bl_manifold_final_aether and localize("manifold_played_hand") or localize("ph_unscored_hand"), maxw = 9, colours = {G.C.WHITE}, float = true, shadow = true, silent = true, pop_in = 0, pop_in_rate = 6}}},
'''

# Game:update_hand_played
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
if G.GAME.chips - G.GAME.blind.chips >= 0 or G.GAME.current_round.hands_left < 1 then
    G.STATE = G.STATES.NEW_ROUND
'''
position = "at"
match_indent = true
payload = '''
if G.GAME.current_round.hands_left < 1 then
    G.STATE = G.STATES.NEW_ROUND
elseif G.GAME.chips >= G.GAME.blind.chips then
    if G.GAME.round_resets.blind == G.P_BLINDS.bl_manifold_final_aether then
        local count = 0
        for k, v in pairs(G.GAME.blind.hands) do
            count = count + 1
        end
        if count < math.max(math.min(5, G.GAME.round_resets.hands), 0) then
            G.STATE = G.STATES.DRAW_TO_HAND
        else
            G.STATE = G.STATES.NEW_ROUND
        end
    else
        G.STATE = G.STATES.NEW_ROUND
    end
'''