[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Adds silence condition
# SMODS.destroy_cards
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "return card:start_dissolve(args.colours) ~= false"
position = "at"
match_indent = true
payload = '''
return card:start_dissolve(args.colours, args.should_silence and args.should_silence(args.i)) ~= false
'''

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "if args.immediate then"
position = "before"
match_indent = true
payload = '''
args.i = i
'''

# Update blind text on "reset" (ex: selling Oops)
# Blind:set_blind
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = "if not reset then"
position = "at"
match_indent = true
payload = '''
if reset then
    self:set_text()
else
'''

# Fix save + reload of SMODS.Gradient (ex: when using for Suit color)
# recursive_table_cull
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = 'if v.is and v:is(Object) then ret_t[k] = [["]].."MANUAL_REPLACE"..[["]]'
position = "at"
match_indent = true
payload = '''
if v.is then
    if v:is(SMODS.Gradient) then
        ret_t[k] = v.key
    elseif v:is(Object) then
        ret_t[k] = '"MANUAL_REPLACE"'
    end
'''

# UIElement:draw_self
[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = "if self.config.colour[4] > 0.01 then"
position = "before"
match_indent = true
payload = '''
if not self.config.colour[4] then self.config.colour = SMODS.Gradients[self.config.colour] end
'''