[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Adds silence condition
# SMODS.destroy_cards
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "return card:start_dissolve(args.colours) ~= false"
position = "at"
match_indent = true
payload = '''
return card:start_dissolve(args.colours, args.should_silence and args.should_silence(args.i)) ~= false
'''

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "if args.immediate then"
position = "before"
match_indent = true
payload = '''
args.i = i
'''

# Update blind text on "reset" (ex: selling Oops)
# Blind:set_blind
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = "if not reset then"
position = "at"
match_indent = true
payload = '''
if reset then
    self:set_text()
else
'''

# Fix save + reload of SMODS.Gradient (ex: when using for Suit color)
# recursive_table_cull
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = 'if v.is and v:is(Object) then ret_t[k] = [["]].."MANUAL_REPLACE"..[["]]'
position = "at"
match_indent = true
payload = '''
if v.is and v:is(Object) then
    if v:is(SMODS.Gradient) then
        ret_t[k] = v.key
    else
        ret_t[k] = '"MANUAL_REPLACE"'
    end
'''

# UIElement:draw_self
[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = "if self.config.colour[4] > 0.01 then"
position = "before"
match_indent = true
payload = '''
if not self.config.colour[4] then self.config.colour = SMODS.Gradients[self.config.colour] end
'''

# Fix SMODS multi-page deck view tallying rankless and suitless cards
# G.funcs.your_suits_page
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = "if v.base.suit then suit_tallies[v.base.suit] = (suit_tallies[v.base.suit] or 0) + 1 end"
position = "at"
match_indent = true
payload = '''
if v.base.suit and not SMODS.has_no_suit(v) then suit_tallies[v.base.suit] = (suit_tallies[v.base.suit] or 0) + 1 end
'''

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = '''
if v.base.value then face_tally = face_tally + ((SMODS.Ranks[v.base.value].face) and 1 or 0) end
mod_face_tally = mod_face_tally + (v:is_face() and 1 or 0)
if v.base.value and not SMODS.Ranks[v.base.value].face and card_id ~= 14 then
    num_tally = num_tally + 1
    if not v.debuff then mod_num_tally = mod_num_tally + 1 end
end
if card_id == 14 then
    ace_tally = ace_tally + 1
    if not v.debuff then mod_ace_tally = mod_ace_tally + 1 end
end

--ranks
if v.base.value then rank_tallies[v.base.value] = rank_tallies[v.base.value] + 1 end
if v.base.value and not v.debuff then mod_rank_tallies[v.base.value] = mod_rank_tallies[v.base.value] + 1 end
'''
position = "at"
match_indent = true
payload = '''
local v_nr = SMODS.has_no_rank(v)
if v.base.value and not v_nr and SMODS.Ranks[v.base.value].face then face_tally = face_tally + 1 end
mod_face_tally = mod_face_tally + (v:is_face() and 1 or 0)
if v.base.value and not v_nr and not SMODS.Ranks[v.base.value].face and card_id ~= 14 then num_tally = num_tally + 1 end
if v:is_number(true) then mod_num_tally = mod_num_tally + 1 end
if card_id == 14 then ace_tally = ace_tally + 1 end
if v:is_rank(14, true) then mod_ace_tally = mod_ace_tally + 1 end

--ranks
if v.base.value and not v_nr then rank_tallies[v.base.value] = rank_tallies[v.base.value] + 1 end
for kk, vv in ipairs(rank_name_mapping) do
    if v:is_rank(SMODS.Ranks[vv].id, true) then mod_rank_tallies[vv] = mod_rank_tallies[vv] + 1 end
end
'''

# Add seal chance to Vanilla Illusion and make Edition chance scale with Hone
# create_card_for_shop
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
if (v.type == 'Base' or v.type == 'Enhanced') and G.GAME.used_vouchers["v_illusion"] and pseudorandom(pseudoseed('illusion')) > 0.8 then 
    card:set_edition(poll_edition('illusion', nil, true, true))
'''
position = "at"
match_indent = true
payload = '''
if (v.type == "Base" or v.type == "Enhanced") and G.GAME.used_vouchers.v_illusion then
    card:set_seal(SMODS.poll_seal({key = "illusion", mod = 10}), true, true)
    card:set_edition(poll_edition("illusion", 5, true))
'''