[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Card:add_to_deck
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.added_to_deck = true"
position = "after"
match_indent = true
payload = '''
G.GAME.era = (G.GAME.era or 0) + 1
self.ability.era = G.GAME.era
'''