[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# localize
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "detailed_tooltip = part.control.T and (G.P_CENTERS[part.control.T] or G.P_TAGS[part.control.T]) or nil,"
position = "at"
match_indent = true
payload = '''
detailed_tooltip = part.control.T and (G.P_CENTERS[part.control.T] or G.P_TAGS[part.control.T] or MANIF.tooltips[part.control.T]) or nil,
'''