[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Game:init_item_prototypes
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''e_negative =   {order = 5,  unlocked = true, discovered = false, name = "Negative", pos = {x=0,y=0}, atlas = 'Joker', set = "Edition", config = {extra = 1}},'''
position = "after"
match_indent = true
payload = '''
e_negative_playing_card = {order = 6, name = "Negative", set = "Edition", config = {extra = 1}},
e_negative_planet = {order = 7, name = "Negative", set = "Edition", config = {extra = 1}},
'''