[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Card:calculate_joker
# Sixth Sense
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Sixth Sense' and #context.full_hand == 1 and context.full_hand[1]:get_id() == 6 and G.GAME.current_round.hands_played == 0 then"
position = "at"
match_indent = true
payload = '''
if self.ability.name == "Sixth Sense" and #context.full_hand == 1 and context.full_hand[1]:is_rank(6) and G.GAME.current_round.hands_played == 0 then
'''

# Mail in Rebate
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "context.other_card:get_id() == G.GAME.current_round.mail_card.id then"
position = "at"
match_indent = true
payload = '''
context.other_card:is_rank(G.GAME.current_round.mail_card.id) then
'''

# Hit the Road
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "context.other_card:get_id() == 11 and not context.blueprint then"
position = "at"
match_indent = true
payload = '''
context.other_card:is_rank(11) and not context.blueprint then
'''

# Wee Joker
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "context.other_card:get_id() == 2 and not context.blueprint then"
position = "at"
match_indent = true
payload = '''
context.other_card:is_rank(2) and not context.blueprint then
'''

# 8 Ball
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if (context.other_card:get_id() == 8) and (SMODS.pseudorandom_probability(self, '8ball', 1, self.ability.extra)) then"
position = "at"
match_indent = true
payload = '''
if (context.other_card:is_rank(8)) and (SMODS.pseudorandom_probability(self, '8ball', 1, self.ability.extra)) then
'''

# The Idol
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "context.other_card:get_id() == G.GAME.current_round.idol_card.id and"
position = "at"
match_indent = true
payload = '''
context.other_card:is_rank(G.GAME.current_round.idol_card.id) and
'''

# Scholar
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "context.other_card:get_id() == 14 then"
position = "at"
match_indent = true
payload = '''
context.other_card:is_rank(14) then
'''

# Walkie Talkie
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "(context.other_card:get_id() == 10 or context.other_card:get_id() == 4) then"
position = "at"
match_indent = true
payload = '''
(context.other_card:is_rank(10) or context.other_card:is_rank(4)) then
'''

# Fibonacci
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
context.other_card:get_id() == 2 or
    context.other_card:get_id() == 3 or
    context.other_card:get_id() == 5 or
    context.other_card:get_id() == 8 or
    context.other_card:get_id() == 14) then
'''
position = "at"
match_indent = true
payload = '''
context.other_card:is_rank(2) or
    context.other_card:is_rank(3) or
    context.other_card:is_rank(5) or
    context.other_card:is_rank(8) or
    context.other_card:is_rank(14)) then
'''

# Triboulet
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "(context.other_card:get_id() == 12 or context.other_card:get_id() == 13) then"
position = "at"
match_indent = true
payload = '''
(context.other_card:is_rank(12) or context.other_card:is_rank(13)) then
'''

# Shoot the Moon
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "context.other_card:get_id() == 12 then"
position = "at"
match_indent = true
payload = '''
context.other_card:is_rank(12) then
'''

# Baron
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "context.other_card:get_id() == 13 then"
position = "at"
match_indent = true
payload = '''
context.other_card:is_rank(13) then
'''

# Hack
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
context.other_card:get_id() == 2 or
    context.other_card:get_id() == 3 or
    context.other_card:get_id() == 4 or
    context.other_card:get_id() == 5) then
'''
position = "at"
match_indent = true
payload = '''
context.other_card:is_rank(2) or
    context.other_card:is_rank(3) or
    context.other_card:is_rank(4) or
    context.other_card:is_rank(5)) then
'''

# Cloud 9
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if v:get_id() == 9 then self.ability.nine_tally = self.ability.nine_tally+1 end"
position = "at"
match_indent = true
payload = '''
if v:is_rank(9) then self.ability.nine_tally = self.ability.nine_tally + 1 end
'''

# Even Steven
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
context.other_card:get_id() <= 10 and
context.other_card:get_id() >= 0 and
context.other_card:get_id()%2 == 0
'''
position = "at"
match_indent = true
payload = '''
context.other_card:is_even()
'''

# Odd Todd
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
((context.other_card:get_id() <= 10 and
    context.other_card:get_id() >= 0 and
    context.other_card:get_id()%2 == 1) or
    (context.other_card:get_id() == 14))
'''
position = "at"
match_indent = true
payload = '''
context.other_card:is_odd()
'''

# G.UIDEF.view_deck
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = '''
if v.base.value and not v_nr and not SMODS.Ranks[v.base.value].face and card_id ~= 14 then
    num_tally = num_tally + 1
    if not v.debuff then mod_num_tally = mod_num_tally + 1 end
end
if card_id == 14 then
    ace_tally = ace_tally + 1
    if not v.debuff then mod_ace_tally = mod_ace_tally + 1 end
end

--ranks
if v.base.value and not v_nr then rank_tallies[v.base.value] = rank_tallies[v.base.value] + 1 end
if v.base.value and not v_nr and not v.debuff then mod_rank_tallies[v.base.value] = mod_rank_tallies[v.base.value] + 1 end
'''
position = "at"
match_indent = true
payload = '''
if v.base.value and not v_nr and not SMODS.Ranks[v.base.value].face and card_id ~= 14 then num_tally = num_tally + 1 end
if v:is_number() then mod_num_tally = mod_num_tally + 1 end
if card_id == 14 then ace_tally = ace_tally + 1 end
if v:is_rank(14) then mod_ace_tally = mod_ace_tally + 1 end

--ranks
for kk, vv in ipairs(rank_name_mapping) do
    if card_id == SMODS.Ranks[vv].id then rank_tallies[vv] = rank_tallies[vv] + 1 end
    if v:is_rank(SMODS.Ranks[vv].id) then mod_rank_tallies[vv] = mod_rank_tallies[vv] + 1 end
end
'''