[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# calculate_individual_effect
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "if (key == 'x_mult' or key == 'xmult' or key == 'Xmult' or key == 'x_mult_mod' or key == 'Xmult_mod') and amount ~= 1 then"
position = "at"
match_indent = true
payload = '''
if (key == "x_mult" or key == "xmult" or key == "Xmult" or key == "x_mult_mod" or key == "Xmult_mod") and (amount ~= 1 or effect.forced) then
'''

# card_eval_status_text
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if amt > 0 or amt < 0 then"
position = "at"
match_indent = true
payload = '''
if amt ~= 0 or eval_type == "x_mult" then
'''