[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[vars]
num = '(next(SMODS.find_card("j_manifold_orange_juice")) and 1 or G.GAME.probabilities.normal)'
den = 'next(SMODS.find_card("j_manifold_orange_juice")) and 1 or'

# Lucky Card
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if pseudorandom('lucky_mult') < G.GAME.probabilities.normal/5 then"
position = "at"
match_indent = true
payload = '''
if pseudorandom("lucky_mult") < G.GAME.probabilities.normal / 5 or self.guaranteed_mult then
'''

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if pseudorandom('lucky_money') < G.GAME.probabilities.normal/15 then"
position = "at"
match_indent = true
payload = '''
if pseudorandom("lucky_money") < G.GAME.probabilities.normal / 15 or self.guaranteed_money then
'''

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "elseif _c.effect == 'Lucky Card' then loc_vars = {G.GAME.probabilities.normal, cfg.mult, 5, cfg.p_dollars, 15}"
position = "at"
match_indent = true
payload = '''
elseif _c.effect == "Lucky Card" then loc_vars = {{{lovely:num}}, cfg.mult, {{lovely:den}} 5, cfg.p_dollars, {{lovely:den}} 15}
'''

# Glass Card
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "elseif _c.effect == 'Glass Card' then loc_vars = {cfg.Xmult, G.GAME.probabilities.normal, cfg.extra}"
position = "at"
match_indent = true
payload = '''
elseif _c.effect == "Glass Card" then loc_vars = {cfg.Xmult, {{lovely:num}}, {{lovely:den}} cfg.extra}
'''

# The Wheel of Fortune
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = 'elseif _c.name == "The Wheel of Fortune" then loc_vars = {G.GAME.probabilities.normal, cfg.extra};  info_queue[#info_queue+1] = G.P_CENTERS.e_foil; info_queue[#info_queue+1] = G.P_CENTERS.e_holo; info_queue[#info_queue+1] = G.P_CENTERS.e_polychrome;'
position = "at"
match_indent = true
payload = '''
elseif _c.name == "The Wheel of Fortune" then loc_vars = {{{lovely:num}}, {{lovely:den}} cfg.extra};  info_queue[#info_queue+1] = G.P_CENTERS.e_foil; info_queue[#info_queue+1] = G.P_CENTERS.e_holo; info_queue[#info_queue+1] = G.P_CENTERS.e_polychrome;
'''

# Space Joker
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "elseif self.ability.name == 'Space Joker' then loc_vars = {''..(G.GAME and G.GAME.probabilities.normal or 1), self.ability.extra}"
position = "at"
match_indent = true
payload = '''
elseif self.ability.name == "Space Joker" then loc_vars = {{{lovely:num}}, {{lovely:den}} self.ability.extra}
'''

# 8 Ball
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "elseif self.ability.name == '8 Ball' then loc_vars = {''..(G.GAME and G.GAME.probabilities.normal or 1),self.ability.extra}"
position = "at"
match_indent = true
payload = '''
elseif self.ability.name == "8 Ball" then loc_vars = {{{lovely:num}}, {{lovely:den}} self.ability.extra}
'''

# Gros Michel
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "elseif self.ability.name == 'Gros Michel' then loc_vars = {self.ability.extra.mult, ''..(G.GAME and G.GAME.probabilities.normal or 1), self.ability.extra.odds}"
position = "at"
match_indent = true
payload = '''
elseif self.ability.name == "Gros Michel" then loc_vars = {self.ability.extra.mult, {{lovely:num}}, {{lovely:den}} self.ability.extra.odds}
'''

# Business Card
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "elseif self.ability.name == 'Business Card' then loc_vars = {''..(G.GAME and G.GAME.probabilities.normal or 1), self.ability.extra}"
position = "at"
match_indent = true
payload = '''
elseif self.ability.name == "Business Card" then loc_vars = {{{lovely:num}}, {{lovely:den}} self.ability.extra}
'''

# Bloodstone
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "elseif self.ability.name == 'Bloodstone' then loc_vars = {''..(G.GAME and G.GAME.probabilities.normal or 1), self.ability.extra.odds, self.ability.extra.Xmult}"
position = "at"
match_indent = true
payload = '''
elseif self.ability.name == "Bloodstone" then loc_vars = {{{lovely:num}}, {{lovely:den}} self.ability.extra.odds, self.ability.extra.Xmult}
'''

# Cavendish
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "elseif self.ability.name == 'Cavendish' then loc_vars = {self.ability.extra.Xmult, ''..(G.GAME and G.GAME.probabilities.normal or 1), self.ability.extra.odds}"
position = "at"
match_indent = true
payload = '''
elseif self.ability.name == "Cavendish" then loc_vars = {self.ability.extra.Xmult, {{lovely:num}}, {{lovely:den}} self.ability.extra.odds}
'''

# Reserve Parking
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "elseif self.ability.name == 'Reserved Parking' then loc_vars = {self.ability.extra.dollars, ''..(G.GAME and G.GAME.probabilities.normal or 1), self.ability.extra.odds}"
position = "at"
match_indent = true
payload = '''
elseif self.ability.name == "Reserved Parking" then loc_vars = {self.ability.extra.dollars, {{lovely:num}}, {{lovely:den}} self.ability.extra.odds}
'''

# Hallucination
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "elseif self.ability.name == 'Hallucination' then loc_vars = {G.GAME.probabilities.normal, self.ability.extra}"
position = "at"
match_indent = true
payload = '''
elseif self.ability.name == "Hallucination" then loc_vars = {{{lovely:num}}, {{lovely:den}} self.ability.extra}
'''