[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# set_debuff
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.perishable and self.ability.perish_tally <= 0 then "
position = "at"
match_indent = true
payload = '''
if self.ability.perishable and self.ability.perish_tally <= 0 or self.ability.set == "Joker" and self.config.center.rarity ~= 1 and self.config.center.rarity ~= "Common" and next(SMODS.find_card("j_manifold_propaganda")) and SMODS.find_card("j_manifold_propaganda")[1] ~= self then
'''