[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[vars]
proso = 'next(SMODS.find_card("j_manifold_prosopagnosia"))'
face_proso = 'context.other_card:is_face() and next(SMODS.find_card("j_manifold_prosopagnosia"))'

# get_straight
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = "min_length = min_length or 5"
position = "before"
match_indent = true
payload = '''
if next(SMODS.find_card("j_pareidolia")) and {{lovely:proso}} then return {} end
'''

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = "for _,v in ipairs(rank.next) do"
position = "at"
match_indent = true
payload = '''
for _,v in ipairs({{lovely:proso}} and PROSO.next[key] or rank.next) do
'''

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = "for _,w in ipairs(SMODS.Ranks[v].next) do"
position = "at"
match_indent = true
payload = '''
for _,w in ipairs({{lovely:proso}} and PROSO.next[v] or SMODS.Ranks[v].next) do
'''

# get_X_same
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "for i=#hand, 1, -1 do"
position = "before"
match_indent = true
payload = '''
if {{lovely:proso}} then vals[SMODS.Rank.max_id.value + 1] = {} end
'''

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "if hand[i]:get_id() == hand[j]:get_id() and i ~= j then"
position = "at"
match_indent = true
payload = '''
if (hand[i]:get_id() == hand[j]:get_id() or hand[i]:is_face() and hand[j]:is_face() and {{lovely:proso}}) and i ~= j then
'''

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "vals[curr[1]:get_id()] = curr"
position = "at"
match_indent = true
payload = '''
    vals[{{lovely:proso}} and SMODS.Rank.max_id.value + 1 or curr[1]:get_id()] = curr
'''

# Hit the Road
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "context.other_card:get_id() == 11 and not context.blueprint then"
position = "at"
match_indent = true
payload = '''
(context.other_card:get_id() == 11 or {{lovely:face_proso}}) and not context.blueprint then
'''

# Shoot the Moon
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "context.other_card:get_id() == 12 then"
position = "at"
match_indent = true
payload = '''
(context.other_card:get_id() == 12 or {{lovely:face_proso}}) then
'''

# Triboulet
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "(context.other_card:get_id() == 12 or context.other_card:get_id() == 13) then"
position = "at"
match_indent = true
payload = '''
(context.other_card:get_id() == 12 or context.other_card:get_id() == 13 or {{lovely:face_proso}}) then
'''

# Baron
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "context.other_card:get_id() == 13 then"
position = "at"
match_indent = true
payload = '''
(context.other_card:get_id() == 13 or {{lovely:face_proso}}) then
'''