[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# ease_ante
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "G.GAME.round_resets.ante = G.GAME.round_resets.ante + mod"
position = "after"
match_indent = true
payload = '''
check_for_unlock{type = "ease_ante", ante = G.GAME.round_resets.ante}
'''

# sacrifice
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "local sliced_card = G.jokers.cards[my_pos+1]"
position = "after"
match_indent = true
payload = '''
check_for_unlock{type = "sacrifice", name = sliced_card.ability.name}
'''